# Generated by Django 3.1.4 on 2021-01-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210118_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='E:/git/cw2/pets_back/media'),
        ),
    ]
