# Generated by Django 3.1.4 on 2021-01-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210118_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
